import type { OutfitTemplate } from "@/domain/types";

export const OUTFIT_TEMPLATES: OutfitTemplate[] = [
  {
    id: "hot-commute-01",
    thermalBand: "hot",
    scenes: ["commute", "travel"],
    label: "清爽机能",
    styleTags: ["透气", "利落"],
    rationale: "轻薄单层减少闷热，鞋履适合日常步行。",
    items: [
      { id: "white-tee", name: "白色轻薄短袖", category: "top", icon: "tee", color: "奶白" },
      { id: "black-shorts", name: "黑色速干短裤", category: "bottom", icon: "shorts", color: "黑色" },
      { id: "grey-sneaker", name: "灰色透气运动鞋", category: "shoes", icon: "sneaker", color: "浅灰" },
    ],
  },
  {
    id: "hot-date-01",
    audiences: ["womens"],
    thermalBand: "hot",
    scenes: ["date"],
    label: "轻甜街头",
    styleTags: ["清爽", "有型"],
    rationale: "用干净廓形保持轻盈，避免过多叠穿。",
    items: [
      { id: "mint-tee", name: "薄荷绿合身短袖", category: "top", icon: "tee", color: "薄荷绿" },
      { id: "grey-skirt", name: "灰色轻量半裙", category: "bottom", icon: "skirt", color: "灰色" },
      { id: "white-sneaker", name: "白色低帮鞋", category: "shoes", icon: "sneaker", color: "白色" },
    ],
  },
  {
    id: "warm-commute-01",
    thermalBand: "warm",
    scenes: ["commute", "travel"],
    label: "城市轻装",
    styleTags: ["轻量", "通勤"],
    rationale: "短袖加长下装，应对室内空调与户外温差。",
    items: [
      { id: "charcoal-tee", name: "炭灰色短袖", category: "top", icon: "tee", color: "炭灰" },
      { id: "khaki-pants", name: "卡其轻薄长裤", category: "bottom", icon: "pants", color: "卡其" },
      { id: "black-sneaker", name: "黑色运动鞋", category: "shoes", icon: "sneaker", color: "黑色" },
    ],
  },
  {
    id: "warm-date-01",
    thermalBand: "warm",
    scenes: ["date"],
    label: "干净松弛",
    styleTags: ["简洁", "松弛"],
    rationale: "薄衬衫的层次感更适合约会，也方便卷袖调节。",
    items: [
      { id: "blue-shirt", name: "雾蓝薄衬衫", category: "top", icon: "shirt", color: "雾蓝" },
      { id: "cream-pants", name: "米白直筒裤", category: "bottom", icon: "pants", color: "米白" },
      { id: "grey-sneaker-2", name: "浅灰休闲鞋", category: "shoes", icon: "sneaker", color: "浅灰" },
    ],
  },
  {
    id: "mild-commute-01",
    thermalBand: "mild",
    scenes: ["commute", "travel"],
    label: "薄层通勤",
    styleTags: ["层次", "全天候"],
    rationale: "薄长袖可覆盖早晚微凉，保留轻快的城市感。",
    items: [
      { id: "cream-shirt", name: "奶油色长袖衬衫", category: "top", icon: "shirt", color: "奶油白" },
      { id: "black-pants", name: "黑色直筒长裤", category: "bottom", icon: "pants", color: "黑色" },
      { id: "silver-sneaker", name: "银灰运动鞋", category: "shoes", icon: "sneaker", color: "银灰" },
    ],
  },
  {
    id: "mild-date-01",
    audiences: ["womens"],
    thermalBand: "mild",
    scenes: ["date"],
    label: "柔和简约",
    styleTags: ["温柔", "精致"],
    rationale: "针织与半裙提供柔和质感，温度变化时也不单薄。",
    items: [
      { id: "pink-sweater", name: "灰粉薄针织", category: "top", icon: "sweater", color: "灰粉" },
      { id: "charcoal-skirt", name: "炭灰半裙", category: "bottom", icon: "skirt", color: "炭灰" },
      { id: "white-sneaker-2", name: "白色休闲鞋", category: "shoes", icon: "sneaker", color: "白色" },
    ],
  },
  {
    id: "cool-commute-01",
    thermalBand: "cool",
    scenes: ["commute", "travel"],
    label: "轻机能叠穿",
    styleTags: ["防风", "可脱"],
    rationale: "可脱外套应对早晚与室内外温差。",
    items: [
      { id: "grey-longtee", name: "浅灰长袖打底", category: "top", icon: "shirt", color: "浅灰" },
      { id: "black-jacket", name: "黑色轻量夹克", category: "outerwear", icon: "jacket", color: "黑色" },
      { id: "olive-pants", name: "橄榄绿工装裤", category: "bottom", icon: "pants", color: "橄榄绿" },
      { id: "black-sneaker-2", name: "黑色运动鞋", category: "shoes", icon: "sneaker", color: "黑色" },
    ],
  },
  {
    id: "cool-date-01",
    thermalBand: "cool",
    scenes: ["date"],
    label: "复古层次",
    styleTags: ["质感", "约会"],
    rationale: "短夹克与针织形成清晰层次，保暖但不臃肿。",
    items: [
      { id: "cream-sweater", name: "米白薄针织", category: "top", icon: "sweater", color: "米白" },
      { id: "brown-jacket", name: "棕色短夹克", category: "outerwear", icon: "jacket", color: "棕色" },
      { id: "charcoal-pants", name: "炭灰长裤", category: "bottom", icon: "pants", color: "炭灰" },
      { id: "cream-sneaker", name: "奶白休闲鞋", category: "shoes", icon: "sneaker", color: "奶白" },
    ],
  },
  {
    id: "cold-commute-01",
    thermalBand: "cold",
    scenes: ["commute", "travel", "date"],
    label: "暖感街头",
    styleTags: ["保暖", "利落"],
    rationale: "针织加结构感外套兼顾保暖和城市廓形。",
    items: [
      { id: "black-sweater", name: "黑色中厚针织", category: "top", icon: "sweater", color: "黑色" },
      { id: "grey-coat", name: "深灰短呢外套", category: "outerwear", icon: "coat", color: "深灰" },
      { id: "black-pants-2", name: "黑色厚长裤", category: "bottom", icon: "pants", color: "黑色" },
      { id: "grey-boot", name: "灰色短靴", category: "shoes", icon: "boot", color: "灰色" },
    ],
  },
  {
    id: "freezing-commute-01",
    thermalBand: "freezing",
    scenes: ["commute", "travel", "date"],
    label: "轻量御寒",
    styleTags: ["锁温", "不臃肿"],
    rationale: "保暖内层与轻羽绒锁住热量，适合低温移动。",
    items: [
      { id: "thermal-top", name: "黑色保暖打底", category: "top", icon: "sweater", color: "黑色" },
      { id: "silver-down", name: "银灰轻羽绒", category: "outerwear", icon: "down", color: "银灰" },
      { id: "fleece-pants", name: "深灰加绒长裤", category: "bottom", icon: "pants", color: "深灰" },
      { id: "black-boot", name: "黑色短靴", category: "shoes", icon: "boot", color: "黑色" },
    ],
  },
  {
    id: "severe-commute-01",
    thermalBand: "severe",
    scenes: ["commute", "travel", "date"],
    label: "完整冬季防护",
    styleTags: ["强保暖", "防风"],
    rationale: "重型外套与厚底鞋减少低温和冷风带来的热量流失。",
    items: [
      { id: "thermal-heavy", name: "深色厚保暖层", category: "top", icon: "sweater", color: "深灰" },
      { id: "black-heavy-down", name: "黑色长款羽绒服", category: "outerwear", icon: "down", color: "黑色" },
      { id: "winter-pants", name: "黑色防风厚裤", category: "bottom", icon: "pants", color: "黑色" },
      { id: "winter-boot", name: "防滑保暖靴", category: "shoes", icon: "boot", color: "黑色" },
    ],
  },
  {
    id: "hot-all-02",
    thermalBand: "hot",
    scenes: ["commute", "date", "travel"],
    label: "高温留白",
    styleTags: ["极简", "速干"],
    rationale: "用浅色短袖和宽松下装减少吸热，保持空气流动。",
    items: [
      { id: "ice-tee", name: "冰灰速干短袖", category: "top", icon: "tee", color: "冰灰" },
      { id: "navy-shorts", name: "藏蓝宽松短裤", category: "bottom", icon: "shorts", color: "藏蓝" },
      { id: "white-runner", name: "白色网面跑鞋", category: "shoes", icon: "sneaker", color: "白色" },
    ],
  },
  {
    id: "warm-all-02",
    thermalBand: "warm",
    scenes: ["commute", "date", "travel"],
    label: "松弛日常",
    styleTags: ["透气", "舒展"],
    rationale: "透气上装搭配轻薄长裤，室内外都不会过分单薄。",
    items: [
      { id: "cream-polo", name: "米白轻薄上衣", category: "top", icon: "tee", color: "米白" },
      { id: "graphite-pants", name: "石墨灰垂感长裤", category: "bottom", icon: "pants", color: "石墨灰" },
      { id: "green-sneaker", name: "灰绿休闲鞋", category: "shoes", icon: "sneaker", color: "灰绿" },
    ],
  },
  {
    id: "mild-all-02",
    thermalBand: "mild",
    scenes: ["commute", "date", "travel"],
    label: "衬衫节奏",
    styleTags: ["干净", "灵活"],
    rationale: "薄衬衫可单穿也可当外层，适合温和但有变化的一天。",
    items: [
      { id: "blue-shirt-alt", name: "浅蓝宽松衬衫", category: "top", icon: "shirt", color: "浅蓝" },
      { id: "white-tee-inner", name: "白色短袖内搭", category: "top", icon: "tee", color: "白色" },
      { id: "navy-pants", name: "藏蓝直筒裤", category: "bottom", icon: "pants", color: "藏蓝" },
      { id: "grey-shoes-alt", name: "灰白板鞋", category: "shoes", icon: "sneaker", color: "灰白" },
    ],
  },
  {
    id: "cool-all-02",
    thermalBand: "cool",
    scenes: ["commute", "date", "travel"],
    label: "复古运动层",
    styleTags: ["可脱", "复古"],
    rationale: "卫衣与薄外套形成两级调温，早晚凉时更从容。",
    items: [
      { id: "grey-sweat", name: "麻灰薄卫衣", category: "top", icon: "sweater", color: "麻灰" },
      { id: "navy-jacket", name: "藏蓝教练夹克", category: "outerwear", icon: "jacket", color: "藏蓝" },
      { id: "cream-pants-alt", name: "奶油色长裤", category: "bottom", icon: "pants", color: "奶油白" },
      { id: "retro-sneaker", name: "复古跑鞋", category: "shoes", icon: "sneaker", color: "银灰" },
    ],
  },
  {
    id: "cold-all-02",
    thermalBand: "cold",
    scenes: ["commute", "date", "travel"],
    label: "硬朗暖层",
    styleTags: ["防风", "街头"],
    rationale: "高领打底配工装外套，保持热量同时强化廓形。",
    items: [
      { id: "cream-highneck", name: "米白高领针织", category: "top", icon: "sweater", color: "米白" },
      { id: "olive-coat", name: "橄榄绿工装外套", category: "outerwear", icon: "coat", color: "橄榄绿" },
      { id: "black-heavy-pants", name: "黑色厚直筒裤", category: "bottom", icon: "pants", color: "黑色" },
      { id: "brown-boot", name: "棕色短靴", category: "shoes", icon: "boot", color: "棕色" },
    ],
  },
  {
    id: "freezing-all-02",
    thermalBand: "freezing",
    scenes: ["commute", "date", "travel"],
    label: "冬日撞色",
    styleTags: ["锁温", "亮点"],
    rationale: "暖内层与短羽绒减少热量流失，用低饱和色保留造型感。",
    items: [
      { id: "navy-thermal", name: "藏蓝保暖内层", category: "top", icon: "sweater", color: "藏蓝" },
      { id: "green-down", name: "灰绿色短羽绒", category: "outerwear", icon: "down", color: "灰绿" },
      { id: "grey-winter-pants", name: "深灰保暖裤", category: "bottom", icon: "pants", color: "深灰" },
      { id: "black-winter-sneaker", name: "黑色厚底鞋", category: "shoes", icon: "sneaker", color: "黑色" },
    ],
  },
  {
    id: "severe-all-02",
    thermalBand: "severe",
    scenes: ["commute", "date", "travel"],
    label: "极寒机能层",
    styleTags: ["全防护", "机能"],
    rationale: "长外套、保暖层与防滑鞋形成完整防护，减少皮肤暴露。",
    items: [
      { id: "warm-base-alt", name: "黑色厚保暖打底", category: "top", icon: "sweater", color: "黑色" },
      { id: "grey-long-down", name: "深灰长款羽绒", category: "outerwear", icon: "down", color: "深灰" },
      { id: "thermal-pants-alt", name: "加厚防风长裤", category: "bottom", icon: "pants", color: "黑色" },
      { id: "snow-boot-alt", name: "灰黑防滑雪地靴", category: "shoes", icon: "boot", color: "灰黑" },
    ],
  },
];
